# if(NOT CMAKE_BUILD_TYPE)
#   set(CMAKE_BUILD_TYPE Debug CACHE STRING "Choose build type" FORCE)
# endif()
if(CMAKE_BUILD_TYPE STREQUAL "Debug")
     set(PLATFORM "debug")
elseif(CMAKE_BUILD_TYPE STREQUAL "Release")
    set(PLATFORM "release")
else()
    set(PLATFORM "other")
endif()

if(CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
    set(COMPILENAME "clang")
elseif(CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
    set(COMPILENAME "gcc")
endif()

if(CMAKE_C_COMPILER_ID STREQUAL "Clang")
    set(COMPILENAME "clang")
elseif(CMAKE_C_COMPILER_ID STREQUAL "GNU")
    set(COMPILENAME "gcc")
endif()

set(LIBDIR ${CMAKE_CURRENT_LIST_DIR}/lib/${COMPILENAME}/${PLATFORM})

set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${CMAKE_CURRENT_LIST_DIR}/lib/${COMPILENAME}/${PLATFORM}/${PROJECT_NAME})
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${CMAKE_LIBRARY_OUTPUT_DIRECTORY})
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_CURRENT_LIST_DIR}/build/${COMPILENAME}/${PLATFORM}/${PROJECT_NAME})

set(INCLUDEDIR ${CMAKE_CURRENT_LIST_DIR}/include)

# set(CMAKE_AUTOUIC_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/qt_autouic)
# set(CMAKE_AUTOMOC_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/qt_automoc)
# set(CMAKE_AUTORCC_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/qt_autorcc)
